### ISSUE TITLE
how do i create a onvalue change listener for the number picker? 

### ISSUE THREAD

**Issue by Abhi150688** [hrules6872/HorizontalNumberPicker#1]
I am new to android and I am using your project as a library. I want to implement the onvalue change listener whenever the user changes the value of the number and send it to the server. How can i achieve this?

**Comment by hrules6872** [comment]
I've just updated the included example. Check it out :)

**Comment by Abhi150688** [comment]
Hi, 
thanks for that. Also i wanted to restrict the maximum value of the number picker to 5. I changed the value of the Maximum value to 5 in the class, but on pressing the plus button it still allows to increment the value beyond 5. How can i limit the max value?

**Comment by hrules6872** [comment]
You must use `horizontalNumberPicker.setMaxValue(5);`
I've just tested that method and is working well.
