### ISSUE TITLE
check my features

### ISSUE THREAD

**Issue by amorenew** [hrules6872/HorizontalNumberPicker#3]
Hi
i added
method to control text size - bold - card view - reset
in my fork
https://github.com/amorenew/HorizontalNumberPicker
![counter](https://cloud.githubusercontent.com/assets/2842459/16805900/f85bd602-491a-11e6-9457-415c32fad6b6.png)

**Comment by Hippoi** [comment]
Where I can see the methods, parameters and other characteristics?

Thanks

**Comment by amorenew** [comment]
Hi @Hippoi  in main activity
https://github.com/amorenew/HorizontalNumberPicker/blob/master/horizontalnumberpicker-demo/src/main/java/com/hules/horizontalnumberpicker/demo/MainActivity.java
and in xml layout
https://github.com/amorenew/HorizontalNumberPicker/blob/master/horizontalnumberpicker-demo/src/main/res/layout/activity_main.xml

**Comment by amorenew** [comment]
```
 app:buttonTextBold="true"
        app:buttonTextColor="#000"
        app:buttonTextSize="18"
        app:maxValue="4"
        app:minValue="1"
        app:numberBackgroundColor="@null"
        app:numberTextBold="true"
        app:numberTextColor="#000"
        app:numberTextSize="18"
        app:descriptionBackgroundColor="@null"
        app:descriptionTextBold="false"
        app:descriptionTextColor="#535353"
        app:descriptionTextSize="15"
        app:pickerBackgroundColor="@null"
        app:showLeadingZeros="true"
        app:titleUp="true"
        app:value="1"
        app:valueDescription="Man"
```

**Comment by Hippoi** [comment]
Gracias. Otra pregunta, se puede poner un texto delante o detras de un valor?

**Comment by amorenew** [comment]
sorry i don't know spanish 
but i used google translate
app:titleUp="true"
app:valueDescription="Man"
try it but i think it's top title or before no title after value

**Comment by Hippoi** [comment]
Thank you very much again.
Finally, how can I change the size of the suffix "Man"?

**Comment by amorenew** [comment]
make it man child or banana no limit
more control
        app:descriptionBackgroundColor="@null"
        app:descriptionTextBold="false"
        app:descriptionTextColor="#535353"
        app:descriptionTextSize="15"

**Comment by Hippoi** [comment]
I am very grateful.

**Comment by amorenew** [comment]
you are welcome

**Comment by Hippoi** [comment]
Hello again.

I have placed in my project
    compile 'com.hrules:horizontalnumberpicker:1.1.1'


and

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="48dp">

    <com.hrules.horizontalnumberpicker.HorizontalNumberPicker
        android:id="@+id/horizontal_number_picker2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        app:valueDescription="º"
        app:descriptionBackgroundColor="@null"
        app:descriptionTextBold="false"
        app:descriptionTextColor="#535353"
        app:descriptionTextSize="50"
        />
.....


But when I run it, I get the errors

Error:(37) No resource identifier found for attribute 'valueDescription' in package 'com.ejemplos.ejemplos'
Error:(37) No resource identifier found for attribute 'descriptionBackgroundColor' in package 'com.ejemplos.ejemplos'
Error:(37) No resource identifier found for attribute 'descriptionTextBold' in package 'com.ejemplos.ejemplos'
Error:(37) No resource identifier found for attribute 'descriptionTextColor' in package 'com.ejemplos.ejemplos'
Error:(37) No resource identifier found for attribute 'descriptionTextSize' in package 'com.ejemplos.ejemplos'

Can you help me?
