### ISSUE TITLE
onChage

### ISSUE THREAD

**Issue by Hippoi** [hrules6872/HorizontalNumberPicker#5]
Hola Hector, antes de nada agradecerte tus aportaciones.

Stoy empezando en el mjndo de la programacion en Android, y he encontrado tu HorizontalNumberPicker, lo quiero utilizar pero he intentado hace un evento cada vez que se cambia un valor y la verda es que no se como hacerlo.

Si fuera un NumberPicker normal lo haría asi:

        numberpicker.setOnValueChangedListener(new NumberPicker.OnValueChangeListener() {
            @Override
            public void onValueChange(NumberPicker picker, int oldVal, int newVal) {
                intTemCons= newVal;
            }
        });

Me puede decir como lo haria con tu codigo.

Saludos

**Comment by hrules6872** [comment]
Hola @Hippoi 

lo tienes implementado en la [demo](https://github.com/hrules6872/HorizontalNumberPicker/blob/master/horizontalnumberpicker-demo/src/main/java/com/hules/horizontalnumberpicker/demo/MainActivity.java#L34) ;)

Siguiendo tu ejemplo, aqui tienes:

```
numberpicker.setListener(new HorizontalNumberPickerListener() {
      @Override public void onHorizontalNumberPickerChanged(HorizontalNumberPicker horizontalNumberPicker, int value) {
        intTemCons = value;
      }
    });
```
